import { VerticalBox, CheckBox, AboutSlint } from "std-widgets.slint";

export component AboutWindow inherits Window {
    width: 300px;
    height: 300px;
    icon: @image-url("../assets/app_icon.ico");
    title <=> app-name;
    in property <string> app-name;
    in property <string> app-version;
    in-out property <bool> hidden;
    callback hidden-cb-toggled <=> hidden-cb.toggled;
    VerticalBox {
        HorizontalLayout {
            Image {
                width: 48px;
                height: 48px;
                source: @image-url("../assets/app_icon.ico");
            }

            VerticalBox {
                padding-top: 0px;
                HorizontalLayout {
                    alignment: start;
                    Text {
                        font-weight: 800;
                        text <=> app-name;
                    }

                    Text {
                        text <=> app-version;
                    }
                }

                Text {
                    text: "Copyright © 2008-2025 Dmitry Maluev";
                }
            }
        }

        Text {
            text: "Simple TTS Reader is a small clipboard reader based on Microsoft Speech API.\nMake a selection and press Ctrl+C to copy the text you want to read aloud.\nUse --hidden argument to start in tray-only mode.";
            wrap: word-wrap;
        }

        hidden-cb := CheckBox {
            checked <=> hidden;
            text: "Launch hidden";
        }

        AboutSlint { }
    }
}
