import {
    Palette,
    StyleMetrics,
    GridBox,
    HorizontalBox,
    VerticalBox,
    ComboBox,
    LineEdit,
    Slider,
    StandardListView,
} from "std-widgets.slint";
import {
    MyButton,
    MyOpenButton,
    MyLine,
    MySliderLabel,
    MySliderValue,
} from "my_lib.slint";
import { AboutWindow } from "about_window.slint";
import { DictionaryWindow } from "dictionary_window.slint";

export { AboutWindow, DictionaryWindow }

export component MainWindow inherits Window {
    width: 580px;
    height: 360px;
    background: Palette.alternate-background;
    icon: @image-url("../assets/app_icon.ico");
    title <=> app-name;

    in property <string> app-name;
    in property <[StandardListViewItem]> voices-list-model;
    out property <string> test-string: "This is a test string.";
    in-out property <float> rate: 0;
    in-out property <float> volume: 100;
    in-out property <int> output-cb-current-index <=> output-cb.current-index;
    callback voices-list-current-item-changed <=> voices-list.current-item-changed;
    callback rate-slider-released <=> rate-slider.released;
    callback volume-slider-released <=> volume-slider.released;
    callback about-button-clicked <=> about-button.clicked;
    callback test-button-clicked <=> test-button.clicked;
    callback dict-button-clicked <=> dict-button.clicked;
    callback output-cb-selected <=> output-cb.selected;
    callback output-button-clicked <=> output-button.clicked;
    callback link-ta-clicked <=> link-ta.clicked;
    public function voices-list-set-current-item(index: int) {
        voices-list.set-current-item(index);
    }

    VerticalBox {
        Rectangle {
            background: Palette.control-background;
            border-color: Palette.border;
            border-width: 1px;
            voices-list := StandardListView {
                model <=> voices-list-model;
            }
        }

        GridBox {
            spacing-vertical: StyleMetrics.layout-spacing * 2;

            Row {
                MySliderLabel {
                    text: "Rate:";
                }

                rate-slider := Slider {
                    value <=> rate;
                    minimum: -10;
                    maximum: 10;
                    changed(value) => {
                        if (round(value) == 0) {
                            self.value = 0; // Fix -0
                        } else {
                            self.value = round(value);
                        }
                    }
                }

                MySliderValue {
                    text: "\{round(rate-slider.value)}";
                }
            }

            Row {
                MySliderLabel {
                    text: "Volume:";
                }

                volume-slider := Slider {
                    value <=> volume;
                    changed(value) => {
                        self.value = round(value);
                    }
                }

                MySliderValue {
                    text: "\{round(volume-slider.value)}";
                }
            }
        }

        HorizontalBox {
            about-button := MyButton {
                text: "About";
            }

            test-button := MyButton {
                text: "Test";
            }

            LineEdit {
                text <=> test-string;
                accepted(text) => {
                    test-button-clicked();
                }
            }
        }

        MyLine { }

        HorizontalBox {
            dict-button := MyButton {
                text: "Dictionary";
            }

            output-cb := ComboBox {
                model: ["Speak", "🔴 Save as WAV", "🔴 Save as Opus", "🔴 Save as Ogg Vorbis"];
            }

            output-button := MyOpenButton { }

            link-ta := TouchArea {
                mouse-cursor: pointer;
                Text {
                    color: link-ta.has-hover ? Palette.foreground : Palette.accent-background;
                    font-weight: FontWeight.extra-bold;
                    text: "simplettsreader.sourceforge.io";
                    vertical-alignment: center;
                }
            }
        }
    }
}
