import { Palette, GridBox, HorizontalBox, VerticalBox, Button, ComboBox, LineEdit, Slider, StandardListView } from "std-widgets.slint";
import { AboutWindow } from "about_window.slint";
import { DictionaryWindow } from "dictionary_window.slint";

export { AboutWindow, DictionaryWindow }

export component MainWindow inherits Window {
    width: 580px;
    height: 360px;
    background: Palette.alternate-background;
    icon: @image-url("../assets/app_icon.ico");
    title <=> app-name;
    in property <string> app-name;
    in property <[StandardListViewItem]> voices-list-model;
    out property <string> test-string: "This is a test string.";
    in-out property <float> rate: 0;
    in-out property <float> volume: 100;
    in-out property <int> output-cb-current-index <=> output-cb.current-index;
    callback voices-list-current-item-changed <=> voices-list.current-item-changed;
    callback rate-slider-released <=> rate-slider.released;
    callback volume-slider-released <=> volume-slider.released;
    callback about-button-clicked <=> about-button.clicked;
    callback test-button-clicked <=> test-button.clicked;
    callback dict-button-clicked <=> dict-button.clicked;
    callback output-cb-selected <=> output-cb.selected;
    callback output-button-clicked <=> output-button.clicked;
    callback link-ta-clicked <=> link-ta.clicked;
    public function voices-list-set-current-item(index: int) {
        voices-list.set-current-item(index);
    }
    VerticalBox {
        Rectangle {
            background: Palette.control-background;
            border-color: Palette.border;
            border-width: 1px;
            voices-list := StandardListView {
                model <=> voices-list-model;
            }
        }

        GridBox {
            spacing-vertical: 24px;
            Row {
                Text {
                    width: 64px;
                    text: "Rate:";
                }

                rate-slider := Slider {
                    value <=> rate;
                    minimum: -10;
                    maximum: 10;
                    changed(value) => {
                        if (round(value) == 0) {
                            self.value = 0; // Fix -0
                        } else {
                            self.value = round(value);
                        }
                    }
                }

                Text {
                    width: 32px;
                    horizontal-alignment: center;
                    text: "\{round(rate-slider.value)}";
                }
            }

            Row {
                Text {
                    width: 64px;
                    text: "Volume:";
                }

                volume-slider := Slider {
                    value <=> volume;
                    changed(value) => {
                        self.value = round(value);
                    }
                }

                Text {
                    width: 32px;
                    horizontal-alignment: center;
                    text: "\{round(volume-slider.value)}";
                }
            }
        }

        HorizontalBox {
            about-button := Button {
                width: 102px;
                text: "About";
            }

            test-button := Button {
                width: 102px;
                text: "Test";
            }

            LineEdit {
                text <=> test-string;
            }
        }

        Rectangle {
            height: 1phx;
            background: Palette.border;
        }

        HorizontalBox {
            dict-button := Button {
                width: 102px;
                text: "Dictionary";
            }

            output-cb := ComboBox {
                model: ["Speak", "🔴 Save as WAV", "🔴 Save as Opus", "🔴 Save as Ogg Vorbis"];
            }

            output-button := Button {
                width: 34px;
                text: "...";
            }

            Rectangle {
                width: 0px;
            }

            link-ta := TouchArea {
                mouse-cursor: MouseCursor.pointer;
                Text {
                    color: link-ta.has-hover ? Palette.foreground : #0078d7;
                    font-weight: 800;
                    text: "simplettsreader.sourceforge.io";
                    vertical-alignment: center;
                }
            }
        }
    }
}
